// This file is automatically generated. Do not edit it directly.
import { createClient } from '@supabase/supabase-js';
import type { Database } from './types';

const SUPABASE_URL = "https://pshkevbhdzcqlsrwvide.supabase.co";
const SUPABASE_PUBLISHABLE_KEY = "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6InBzaGtldmJoZHpjcWxzcnd2aWRlIiwicm9sZSI6ImFub24iLCJpYXQiOjE3NDY0NDYzMTIsImV4cCI6MjA2MjAyMjMxMn0.mZHegZYQQBQs9_wNZS7M9IgJdzd8_XWNnmgpsKYfPRA";

// Import the supabase client like this:
// import { supabase } from "@/integrations/supabase/client";

export const supabase = createClient<Database>(SUPABASE_URL, SUPABASE_PUBLISHABLE_KEY);